pipeline {
    environment {
    imagename = "web"
    jenkinsProject = 'webapp-frontend'
  }
    agent any

    stages {

        stage('git-checkout') {
            steps {
		checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git-creds', url: 'https://github.com/git-shivakumar/gravity-assessment.git']]])

            }
        }
        stage('Compile') {
            steps {
                echo 'compile the code based on app techstack'
		sh "mvn test"
             }
        }
		
		stage('Test') {
            steps {
                echo 'testing'
		sh "mvn test"
             }
        }
		
		stage('Build & Package') {
            steps {
                echo 'build artifactory code'
		sh "mvn package"
             }
        }
		
        stage('Build Docker Image') {
            steps {
                sh 'docker build --no-cache -t demo_app:latest .'
             }
        }
		
	stage('Push Docker Image') {
            steps {
		sh "docker push shiva/dockerhub:latest"
            }
        }
		
        stage('Deploy') {
            steps {
                sh "docker run -p 8001:8001 -d demo_app"
             }
        }
    }
}
